live_config_reload = true
import = ["~/.config/alacritty/themes/themes/github_dark_colorblind.toml"]
[bell]
animation = "EaseOutExpo"
duration = 0

[[keyboard.bindings]]
key = "Space"
mods = "Control"
action = "ToggleViMode"


[scrolling]
history = 5000


[colors]
draw_bold_text_with_bright_colors = true

# [[colors.indexed_colors]]
# color = "0xF8BD96"
# index = 16

# [[colors.indexed_colors]]
# color = "0xF5E0DC"
# index = 17

# [colors.bright]
# black = "0x988BA2"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"

[colors.cursor]
cursor = "0xF5E0DC"
text = "0x1E1D2F"

# [colors.normal]
# black = "0x6E6C7E"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"

[colors.primary]
background = "0x1E1D2F"
foreground = "0xD9E0EE"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"
save_to_clipboard = true
[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = false
title = ''
# startup_mode = "Maximized"
opacity = 0.9

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 4
y = 4
